### ISSUE TITLE
About compilation on Mac

### ISSUE THREAD

**Issue by 11510880** [pcarbo/lbfgsb-matlab#9]
Hi, 
It seems that Matlab only can use the Xcode Clang as compiler on Mac. I tried to install gfortran using brew and the 'make mex' went wrong-- the compiler is still using the clang.
![1586467816631](https://user-images.githubusercontent.com/32617825/78942563-ddf76700-7ab1-11ea-883f-e0b505e7beef.jpg)

**Comment by pcarbo** [comment]
Before running mex, you need to configure mex to use the alternative C / Fortran compiler; please see the MathWorks website for instructions on how to do this.
